Part_1: Stylistic and other minor fixes
MarketSquare/robotframework-style-guide pull request #46
Opened 2024-02-16 18:11 UTC by Mko13

2024-02-16 20:27 UTC, guidodemmenie requested changes

2024-02-16 20:39 UTC, Mko13 commented on guides/style_guide.md
> +Library    Builtin
Fixed.

2024-02-16 20:45 UTC, Mko13 commented on guides/style_guide.md
> +Additionally, extra spaces can be used to separate the Builtin, 3rd Party and Custom libraries.
Fixed.

2024-02-17 13:59 UTC, guidodemmenie approved these changes

2024-02-17 17:02 UTC, merged